### ISSUE TITLE
Simple Dunno ?

### ISSUE THREAD

**Issue by inukaze** [MaKiPL/OpenVIII-monogame#142]
Someone know if exist a version similar of this engine but created on (ASM and/or) C++ like main language ?

Because i dont find the way to install "DesktopGL" & "OpenGL" from NuGet, inside MonoDevelop. on the follow distros : 

Slackware 14.2
Slackware64 14.2
Devuan Ascii
GoboLinux
ArtixLinux

and well i don't like things maked with : 
SystemD, PulseAudio, Avahi, C#, VisualBasic, .NET Framework, XNA Framework, Unity (Videogame Engine), Because gave me a lot of headaches just try to run things.

**Comment by Sebanisu** [comment]
I haven't tested Linux in a while because lost a hard drive and have not set it up again. We are still early stages. When we are farther along we can have build scripts made to simplify things. Eventually have pre built packages for the main distros. Another project I saw has automatic builds setup for testing I kind of want to do that so people can just download and try things. You could port this to c++. Though monogame is c# you'd have to replace alot of stuff with native opengl or something. But alot of code is just for reading the ff8 data files putting them in classes and structures that we can use.

**Comment by MaKiPL** [comment]
Closing- not an issue
